version: "3.8"

services:
  konarr:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: konarr
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - data:/data
      - config:/config

volumes:
  data:
  config:

