name: Release

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      mode:
        description: "Please select the bump version"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cargo-publish:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-publish.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-publish.yml@main
    if: ${{ github.event_name == 'push' }}
    secrets: inherit
    with:
      crate: konarr
      crates: konarr,konarr-server,konarr-cli

  patch-release-me:
    uses: 42ByteLabs/.github/.github/workflows/auto-patch-release.yml@main
    if: ${{ github.event_name == 'workflow_dispatch' }}
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      mode: ${{ inputs.mode }}

  container-server:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/container.yml
    uses: 42ByteLabs/.github/.github/workflows/container.yml@main
    if: ${{ github.event_name == 'release' }}
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
    with:
      container-name: "42bytelabs/konarr"
      docker-file: "./server/Dockerfile"

  container-cli:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/container.yml
    uses: 42ByteLabs/.github/.github/workflows/container.yml@main
    if: ${{ github.event_name == 'release' }}
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
    with:
      container-name: "42bytelabs/konarr-cli"
      docker-file: "./cli/Dockerfile"
